config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tasks do
    member do
      get 'sup-tasks', action: :sup_tasks
      get 'sub-tasks', action: :sub_tasks
    end
  end

  # root 'tasks#index'
  root 'home#index'

  # get '/tasks/:id/sup-tasks'
  # get '/tasks/:id/sub-tasks'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :task_dependencies
  # has_many :tasks, through: :task_dependencies

  has_many :sup_task_dependencies, foreign_key: :sub_task_id, class_name: "TaskDependency"
  has_many :sup_tasks, through: :sup_task_dependencies, source: :sup_task

  has_many :sub_task_dependencies, foreign_key: :sup_task_id, class_name: "TaskDependency"
  has_many :sub_tasks, through: :sub_task_dependencies, source: :sub_task

  # def sup_tasks
  #   TaskDependency.find_by('subtask_id' => task.id)
  # end
  #
  # def sub_tasks
  #   task_dependencies
  # end
end

app/models/task_dependency.rb
class TaskDependency < ApplicationRecord
  belongs_to :sup_task, foreign_key: "sup_task_id", class_name: "Task"
  belongs_to :sub_task, foreign_key: "sub_task_id", class_name: "Task"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def edit
    @task = Task.find(params[:id])
  end

  def create
    @task = Task.new(task_params)

    if @task.save
      redirect_to action: 'index'
    else
      render 'new'
    end
  end

  def sup_tasks
    @task = Task.find(params[:id])
    @suptasks = @task.sup_tasks
  end

  def sub_tasks
    @task = Task.find(params[:id])
    @subtasks = @task.sub_tasks
  end

  def update
    @task = Task.find(params[:id])

    if @task.update(task_params)
      redirect_to action: 'index'
    else
      render 'edit'
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path
  end

  private
  def task_params
    params.require(:task).permit(:title, :description, :assignee_id, :due_date, :state)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    title We're here to manage your time effectively!
    = csrf_meta_tags
    = stylesheet_link_tag "application"
    = javascript_include_tag "application"
    = javascript_include_tag "//cdn.tinymce.com/4.4/tinymce.min.js"
  body
    = yield

app/views/tasks/edit.html.slim
.container
  br
  h1 Editing Task
  = simple_form_for :task, url: task_path(@task), method: :patch do |f|
    = f.input :title, required: false
    = f.input :description, as: :text, required: false, input_html: {class: 'tinymce', rows: 10}
    = f.button :submit
  br
  .float-right = link_to 'Back', tasks_path

//ToDo: DRY
//ToDo: Coffeescript
javascript:
  loadTinyMCE = function (selector) {
    try {
      tinymce.remove();
    } catch (err) {
    }
    tinymce.init({
      selector: selector,
      //menubar: false,
      //plugs: 'lists advlist',
      plugins: "link",
      //menubar: "insert",
      //toolbar: "link"
      statusbar: false,
      toolbar_items_size: 'small',
      toolbar: 'undo redo | bold underline italic | bullist numlist | outdent indent | link "',
      theme: 'modern'
      //content_style: "body {background: white !important; padding: 15px}",
      //content_css: "#{asset_path('application.css')}"
    });
  };

  $(function () {
    loadTinyMCE(".tinymce");
  });

app/views/tasks/index.html.slim
css:
  td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
  }

  .active {
    background-color: lightcoral;
  }

  .desc {
    background-color: black;
    color: white;
  }
.container
  br
  br
  - img_adrs= "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRM90mW4Yvpk-c_A9s_wM3WroAmM4tSY4DSWthM4e7AUYS8VOfk"
  img src=img_adrs width="336"
  br
  br
  h1 Listing Tasks
  .float-right = link_to 'New Task', new_task_path
  br
  br

  /.col-sm-12
  /  table
  /    tr
  /      th ID
  /      th Title
  /      th Description
  /      th Sup Tasks
  /      th Sub Tasks
  /      th Show
  /      th Edit
  /      th Destroy
  /    - @tasks.each do |task|
  /      tr
  /        td = task.id
  /        td = task.title
  /        td = raw(task.description)
  /        td = link_to 'Sup', sup_tasks_task_path(task)
  /        td = link_to 'Sub', sub_tasks_task_path(task)
  /        td = link_to 'Show', task_path(task)
  /        td = link_to 'Edit', edit_task_path(task)
  /        td = link_to 'Destroy', task_path(task), method: :delete, data: { confirm: 'Are you sure?' }
  .col-sm-4.float-left
    table
      tr
        th ID
        th Title
      - @tasks.each do |task|
        - title_id = "js-task-title-#{task.id}"
        tr
          td = task.id
          td.js-task-title id=(title_id) = task.title
  .col-sm-8.float-right
    - @tasks.each do |task|
      - desc_id = "js-task-desc-#{task.id}"
      .card.hidden-xl-down.desc id=(desc_id)
        .card-block
          h4.card-title = task.title
          p.card-text = raw(task.description)

      /javascript:
      //  prev_task_id = -1;
      //  $("#js-task-title-#{task.id}").mouseover(function () {
      //    if (prev_task_id > -1) {
      //      $("#js-task-desc-" + prev_task_id).addClass('hidden-xl-down');
      //    }
      //    var curr_task_id = $(this).attr('id').substring('js-task-title-'.length);
      //    var desc_id = "#js-task-desc-" + curr_task_id;
      //    $(desc_id).removeClass('hidden-xl-down');
      //    prev_task_id = curr_task_id;
      //  });

javascript:
  prev_task_id = -1;
  $(".js-task-title").mouseover(function () {

    // Previous Task
    if (prev_task_id > -1) {
      // title
      $("#js-task-title-" + prev_task_id).removeClass('active');

      // desc
      $("#js-task-desc-" + prev_task_id).addClass('hidden-xl-down');
    }

    // Current Task
    var curr_task_id = $(this).attr('id').substring('js-task-title-'.length);

    // title
    $("#js-task-title-" + curr_task_id).addClass('active');

    // desc
    $("#js-task-desc-" + curr_task_id).removeClass('hidden-xl-down');

    // Update Previous Task ID
    prev_task_id = curr_task_id;
  });


/= javascript_include_tag 'jquery-ui-custom-sortable'
/= javascript_include_tag 'jquery.ui.touch-punch.min'
/
/.container
/  br
/  br
/  - img_adrs= "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRM90mW4Yvpk-c_A9s_wM3WroAmM4tSY4DSWthM4e7AUYS8VOfk"
/  img src=img_adrs width="336"
/  br
/  br
/  h1 Listing Tasks
/  h3.float-right = link_to 'New Task', new_task_path
/  br
/  br
/
/  ul#sortable
/    - @tasks.each do |task|
/      - task_id = "task-" + task.id.to_s
/      li.panel
/        = task.id
/        = task.title
/        = raw(task.description)
/        = task.assignee_id
/        = task.state
/        = link_to 'Show', task_path(task)
/        = link_to 'Edit', edit_task_path(task)
/        = link_to 'Destroy', task_path(task), method: :delete, data: { confirm: 'Are you sure?' }
/
/  /ul#sortable
/  /  - @tasks.each do |task|
/  /    - task_id = "task-" + task.id.to_s
/  /    li.row
/  /      .panel
/  /        span.ui-icon.ui-icon-arrowthick-2-n-s
/  /        strong = task.title
/
/  /ul#sortable
/  /  li.ui-state-default
/  /    span.ui-icon.ui-icon-arrowthick-2-n-s
/  /    = "Item 1"
/  /  li.ui-state-default
/  /    span.ui-icon.ui-icon-arrowthick-2-n-s
/  /    = "Item 2"
/  /  li.ui-state-default
/  /    span.ui-icon.ui-icon-arrowthick-2-n-s
/  /    = "Item 3"
/  /  li.ui-state-default
/  /    span.ui-icon.ui-icon-arrowthick-2-n-s
/  /    = "Item 4"
/
/    /tr
/    /  th Draggable
/    /  th Title
/    /  th Description
/    /  th Assignee
/    /  th State
/    /  th Show
/    /  th Edit
/    /  th Destroy
/
/
/
/
//javascript:
//  $(function () {
//    $("#sortable").sortable();
//    $("#sortable").disableSelection();
//  });

/
/  /table
/  /  tr
/  /    th Draggable
/  /    th Title
/  /    th Description
/  /    th Assignee
/  /    th State
/  /    th Show
/  /    th Edit
/  /    th Destroy
/  /  - @tasks.each do |task|
/  /    - task_id = "task-" + task.id.to_s
/  /    tr.panel.panel-default
/  /      td id=task_id ondrop="dropStart(event)" ondragover="dropOver(event)" draggable="true" ondragstart="dragStart(event)" = task.id
/  /      td = task.title
/  /      td = raw(task.description)
/  /      td = task.assignee_id
/  /      td = task.state
/  /      td = link_to 'Show', task_path(task)
/  /      td = link_to 'Edit', edit_task_path(task)
/  /      td = link_to 'Destroy', task_path(task), method: :delete, data: { confirm: 'Are you sure?' }

app/views/tasks/new.html.slim
.container
  br
  h1 New Task
  = simple_form_for @task do |f|
    = f.input :title
    = f.input :description, as: :text, input_html: {class: 'tinymce', rows: 10}
    /= f.input :assignee_id
    /= f.input :due_date
    /= f.input :state
    = f.button :submit
  br
  .float-right = link_to 'Back', tasks_path

//ToDo: DRY
//ToDo: Coffeescript
javascript:
  loadTinyMCE = function (selector) {
    try {
      tinymce.remove();
    } catch (err) {
    }
    tinymce.init({
      selector: selector,
      //menubar: false,
      statusbar: false,
      toolbar_items_size: 'small',
      toolbar: 'undo redo | bold underline italic | bullist numlist | outdent indent',
      theme: 'modern'
      //content_style: "body {background: white !important; padding: 15px}",
      //content_css: "#{asset_path('application.css')}"
    });
  };

  $(function () {
    loadTinyMCE(".tinymce");
  });

app/views/tasks/show.html.slim
.container
  br
  .card
    .card-block
      h3.card-title.text-center = @task.title
      br
      p.card-text = raw(@task.description)
  br
  .float-right = link_to 'Back', tasks_path